### PR TITLE
Add esm support

### PR DESCRIPTION
**Pull request by xiaoxiangmoe**

### CODE REVIEW

**Comment by sindresorhus** [comment]
I appreciate the pull request, but I don't intend to do this to my packages. My plan is to fully switch to ESM for my packages in April when I can target Node.js 12 (because Node.js 10 goes out of LTS).

There's nothing stopping you from using CommonJS from ESM.

**Comment by xiaoxiangmoe** [comment]
@sindresorhus Can I create another PR to add `default` to `index.d.ts`.  This will help someone who has tsconfig `"allowSyntheticDefaultImports": false`.

**Comment by sindresorhus** [comment]
That's discouraged by the TS maintainers. You can just import with `import foo = require('foo')`. I would recommend learning how the TS import stuff works.

**Comment by xiaoxiangmoe** [comment]
@sindresorhus
Sorry, some application bundler, such as vite, snowpack, can only use esm import. So we can't use `import foo = require('foo')`. And I found many library add `default` to `.d.ts`, so I create this PR.

---

This PR includes:
* Modify dts to support `"allowSyntheticDefaultImports": false`
* Add esm, such that users can remove `optimizeDeps: { include: ['array-move'] }` in `vite.config.ts` and angular users will not see commonjs warning in build.

---

If we can't add esm support, can I create a pr to add `default` to `index.d.ts`?

**Comment by sindresorhus** [comment]
> And I found many library add default to .d.ts, so I create this PR.

That is wrong if the package is not ESM.

> If we can't add esm support, can I create a pr to add default to index.d.ts?

No, sorry. This is a problem with your bundler. This package is following the standards. Open an issue on the bundler you use instead.

**Pull request closed without merging**
