### PR TITLE
added support for negative index for 'to' argument

### PR DESCRIPTION
**Pull request by mathewjoe**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Nice! Can you add a test too? :)

**Comment by mathewjoe** [comment]
Sure! :) Shall I directly add them to test.js? I'm pretty new to open source, so I don't know how these things work.. :/

**Comment by sindresorhus** [comment]
Add it below this https://github.com/sindresorhus/array-move/blob/e42d29f1e7f24374c40517ae960cc75d5d98c34d/test.js#L8 with same content as above except for a negative `to` argument.

**Comment by mathewjoe** [comment]
done!

**Comment by sindresorhus** [comment]
Looks good. Thanks :)

**Comment by sindresorhus** [comment]
Check out https://github.com/tiimgreen/github-cheat-sheet for tips on using GitHub ;)

**Comment by mathewjoe** [comment]
You're welcome! And thanks! :)

**Pull request closed without merging**
